# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyTzoker.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 343)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(402, 343))
        MainWindow.setMaximumSize(QtCore.QSize(402, 343))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblOutput = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.lblOutput.setObjectName("lblOutput")
        self.txtOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(10, 40, 381, 241))
        self.txtOutput.setObjectName("txtOutput")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(60, 300, 87, 29))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(150, 300, 87, 29))
        self.btnClear.setObjectName("btnClear")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(240, 300, 87, 29))
        self.btnClose.setObjectName("btnClose")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnClose.clicked.connect(MainWindow.close)
        self.btnClear.clicked.connect(self.txtOutput.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tzoker Calculator"))
        self.lblOutput.setText(_translate("MainWindow", "Output:"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnClose.setText(_translate("MainWindow", "Close"))

